[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'Always repeat' 'Announcements' 'GmsCore support' 'Enable debugging' 'External downloads' 'Copy video URL' 'Swipe controls' 'Enable tablet layout' 'Wide searchbar' 'Tablet mini player'"
